### PR TITLE
Fix sort icon luminosity contrast ratio too low

### PR DESCRIPTION
**Pull request by cRui861**
The sort icon color contrast (5.7:1) is the same as the label as shown in the screenshot below. When clicked, it turns blue.
image

### CODE REVIEW

**Comment by dpwatrous** [comment]
Is the new behavior that the color doesn't change when you focus the column header?

**Comment by cRui861** [comment]
@dpwatrous Yes, the previous behavior made the gray color of the arrows lighter when hovering over the column names so there wasn't as great of a contrast: 
image

**Review by dpwatrous — APPROVED** [review]

**Comment by dpwatrous** [comment]
@cRui861 Gotcha - looks good to me, then!

**Comment by cRui861** [comment]
Included in #2358

**Pull request merged**
