### PR TITLE
Allows users to select browser for authentication

### LINKED ISSUE #2446: Unable to login with an AAD account that have Conditional Access enabled
Ever since our company enabled Conditional Access on our AAD accounts we are no longer able to login in Batch Explorer.

This is the error message:
image

Error Code: 53000
Request Id: *****
Correlation Id: *****
Timestamp: 2022-02-14T13:38:41.083Z
App name: Microsoft Azure CLI
App id: *****
IP address: *****
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered

When looking at the login attempt in Azure AD I can see that it gets rejected because it is not a Compliant device.
Specifically it the **Access controls - Grant Controls** that is rejecting the login attempt.

How can we fix this without enabling all chromium based devices?

### PR DESCRIPTION
**Pull request by gingi**
* Main app window now opens without prior authentication
* New welcome screen prompts user to sign in, while hiding side menu items and allowing the user to access settings
* An overlay prompts the user to authenticate against each tenant that requires interactive authentication, and includes a toggle for using the external (system) browser
* App settings now have ability to toggle external browser for auth
* Upgrades Angular to 11.2.12

Fixes #2446 

image
image

### CODE REVIEW

**Comment by BMurri** [comment]
@gingi Is there anything any of us outside of this team could do to help get this over the finish line?

**Comment by gingi** [comment]
> @gingi Is there anything any of us outside of this team could do to help get this over the finish line?

We are almost done, mostly focusing on some end-to-end testing. In the meantime, you can check out the branch and test it locally. We are trying to cover all scenarios.

**Comment by GBianca** [comment]
@gingi, this is a great update! Are you also planning to take a look at the Windows build? I'm looking forward to having the CA issues fixed on Windows too, but the app is unfortunately not starting

**Comment by MichaCo** [comment]
@gingi I briefly tested this branch and I can actually log in now again.
There was one issue though, I never use Edge and my default browser is Chrome. Chrome seems to now allow access to the  listener on port 3874, I guess because the SSL cert isn't valid?

It works when I change my default browser to Edge. I would never do that voluntarily though, is there some way to make this work with other browsers? 
If that is intentional, because... Microsoft, then you got me good and I finally have to use Edge 😀 
^ kidding

Great work though, waiting for this to get released hopefully soon...?

**Comment by eusebiu** [comment]
I downloaded the pipeline artifacts for windows (https://azurebatch.visualstudio.com/BatchExplorer/_build/results?buildId=8480&view=artifacts&pathAsName=false&type=publishedArtifacts) and if the "Use system browser for authentication" is unchecked, nothing happens when pressing Sign in to Azure or sometimes I get an empty popup.
image

**Comment by gingi** [comment]
> I downloaded the pipeline artifacts for windows (https://azurebatch.visualstudio.com/BatchExplorer/_build/results?buildId=8480&view=artifacts&pathAsName=false&type=publishedArtifacts) and if the "Use system browser for authentication" is unchecked, I get an empty popup when pressing Sign in to Azure. image

Hi @eusebiu. That has just been addressed. Authentication should now be supported both through the built-in window and the system browser (currently Edge).

**Comment by gingi** [comment]
> @gingi I briefly tested this branch and I can actually log in now again. There was one issue though, I never use Edge and my default browser is Chrome. Chrome seems to deny access to the listener on port 3874, I guess because the SSL cert isn't valid?
> 
> It works when I change my default browser to Edge. I would never do that voluntarily though, is there some way to make this work with other browsers? If that is intentional, because... Microsoft, then you got me good and I finally have to use Edge 😀 ^ kidding
> 
> Great work though, waiting for this to get released hopefully soon...?

The PR is pretty much ready and should be merged soon to appear in an upcoming insider build. The issue with Chrome will unfortunately need to be addressed later on, as it requires a service change with Entra, which will allow us to use a custom protocol for the auth redirect URI. Presently we're using `localhost` loopback, which browsers aren't too happy about.

**Comment by BMurri** [comment]
I just tested this, and I'm able to authenticate again It's wonderful, but I cannot use it as-is. My one big remaining problem? I need to be able to select the account I authenticate with: It's NOT the account I'm signed into Windows with, it's a separate account used to isolate access to production systems from people who might steal my credentials without my participation.

When using this, I just get a "... you can close this window" without any opportunity to select which account to use.

**Review by wanghoppe — APPROVED** [review]

**Comment by gingi** [comment]
> I just tested this, and I'm able to authenticate again It's wonderful, but I cannot use it as-is. My one big remaining problem? I need to be able to select the account I authenticate with: It's NOT the account I'm signed into Windows with, it's a separate account used to isolate access to production systems from people who might steal my credentials without my participation.
> 
> When using this, I just get a "... you can close this window" without any opportunity to select which account to use.

I understand. Are you able to visit the Authentication Settings view to select which Entra tenants (or "directories") you want to retrieve Batch accounts from? 
Batch_Explorer

**Comment by gingi** [comment]
@BMurri Here's [a PR](https://github.com/Azure/BatchExplorer/pull/2928) that prompts you to select an account. Let me know if this addresses your issue.

**Comment by gingi** [comment]
@MichaCo [Here's some documentation](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-conditions#chrome-support) on how to make Entra authentication work with non-Edge browsers. Hopefully it's a good stop-gap until our back-end configuration is sorted out.

**Comment by illgitthat** [comment]
> @BMurri Here's [a PR](https://github.com/Azure/BatchExplorer/pull/2928) that prompts you to select an account. Let me know if this addresses your issue.

Wow, what timing when I experience an issue after downloading batch explorer for the first time and see it was fixed a mere 45 mins ago. Thanks @gingi !

Downloading from https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_apis/build/builds/8495/artifacts?artifactName=windows&api-version=7.1&%24format=zip got it working for me.

**Comment by BMurri** [comment]
> @BMurri Here's [a PR](https://github.com/Azure/BatchExplorer/pull/2928) that prompts you to select an account. Let me know if this addresses your issue.

@gingi It works perfectly! Thank you so much!

**Comment by MichaCo** [comment]
> merged soon to appear in an upcoming insider build. The issue with Chrome will unfortunately need to be addressed later on, as it requires a service change with Entra, which will allow us to use a custom protocol for the auth redirect URI. Presently we're using `localhost` loopback, which

Thanks for the link!
Turns out the plugin was already installed on my work laptop, the login flow still did not work though.
Reason was that Chrome auto redirects all http to https calls.

I must have set some hsts policy for localhost, probably by one of our services because I was able to fix it by removing the hsts policy for localhost.

To do so:
* go to chrome://net-internals/#hsts
* type "localhost" in the last box and click delete
image

Now I can login with Chrome, too 🎉

**Comment by illgitthat** [comment]
> > @BMurri Here's [a PR](https://github.com/Azure/BatchExplorer/pull/2928) that prompts you to select an account. Let me know if this addresses your issue.
> 
> Wow, what timing when I experience an issue after downloading batch explorer for the first time and see it was fixed a mere 45 mins ago. Thanks @gingi !
> 
> Downloading from https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_apis/build/builds/8495/artifacts?artifactName=windows&api-version=7.1&%24format=zip got it working for me.

Following up here @gingi - this worked for me on initial download and startup but then when I was timed out / tried to reauthenticate I ran into the same error.

image

**Pull request merged**
