### PR TITLE
Integrate playground into Shared Libraries branch

### PR DESCRIPTION
**Pull request by skapur12**
This PR is to integrate the Shared Component Library playground (a UI component “playground” for developing/testing shared components between Batch Explorer and the Batch portal extension) into the feature/shared-libraries branch. 

The playground exists in a standalone web version and is integrated with the Batch Explorer desktop application.

playground snip

### CODE REVIEW

**Review by dpwatrous — APPROVED** [review]
Thanks again for all your hard work on this @skapur12!

A couple of notes:

I did squash the playground changes down to one commit, and kept others like the fix to Monaco separate. Also removed all of the placeholder demo pages for now (we can re-add as we have actual functioning components to test).

**Comment by dpwatrous** [comment]
@cRui861 let me know if my changes look good to you and we can get this merged to the main shared library branch

**Review by cRui861 — APPROVED** [review]

**Comment by dpwatrous** [comment]
Pushed a fix for the unit test failure

**Pull request merged**
